# Generated by Django 5.2.3 on 2025-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agency_profile_role_alter_profile_bio_profile_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(default='112CC88655', max_length=10, unique=True),
        ),
    ]
