# Generated by Django 5.2.3 on 2025-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_agency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(default='6626653914', max_length=10, unique=True),
        ),
    ]
