# Generated by Django 5.2.3 on 2025-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_agency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(default='3C12DB8E65', max_length=10, unique=True),
        ),
    ]
